name: Continuous integration and deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build prod image
      run: |
        make build-docker IMAGE_TAG=latest
        echo $QUAY_PASSWORD | docker login -u $QUAY_USER --password-stdin quay.io
        make deploy-docker IMAGE_TAG=latest

  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run tests
      run: mvn test
    - name: Build
      run: mvn -B package --file pom.xml -DskipTests=true
    - name: Upload to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        port: 22
        key: ${{ secrets.SSH_KEY }}
        source: "target/social-network-api-1.0-SNAPSHOT.jar"
        target: "/home/${{ secrets.EC2_USERNAME }}"
    - name: Run app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        port: 22
        key: ${{ secrets.SSH_KEY }}
        command_timeout: "20s"
        script: /home/${{ secrets.EC2_USERNAME }}/restart.sh &

