on:
  pull_request:

env:
  DOCKER_IMAGE: quay.io/paulbarrie7/social-network-api
  DOCKER_TAG_DEV: latest



jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master

    - name: Pull the base image
      run: docker pull 

    - name: Build the new image
      run: make build 

    - name: "Security reports"
      uses: dreamquark-ai/ci-security-report@main
      env:
        GITHUB_PAT: ${{secrets.SOCIAL_GITHUB_PAT}}
      with:
        image: 'python'
        base-tag: '3.8-buster'
        new-tag: 'security-test'
        orga: 'adem-m'
        repo: 'adem-msocial-network-api'
        pr-nb: ${{ github.event.number }}
        topic: 'social-network-api'